In [2]:
from tensorflow.keras.preprocessing.text import one_hot



In [4]:
#senetences
sent=[
    'I love my dog',
    'I love my cat',    
    'You love my dog!',
    'Do you think my dog is amazing?',
    'I think my dog is amazing!',
    'your videos are amazing',
    'understand the concept of RNN',
    'RNN is a type of neural network',
 ]

In [ ]:
#define the vocabulary size
voc_size=10000
#one hot representation
onehot_repr=[one_hot(words,voc_size)for words in sent]
print(onehot_repr)#word representation as integers indexes


[[3560, 977, 8012, 9122], [3560, 977, 8012, 9045], [4905, 977, 8012, 9122], [1170, 4905, 8297, 8012, 9122, 3350, 2489], [3560, 8297, 8012, 9122, 3350, 2489], [9105, 28, 8064, 2489], [1086, 6153, 4101, 20, 629], [629, 3350, 3512, 5399, 20, 3198, 5379]]


In [6]:
#word embedding
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)


In [9]:
print(embedded_docs)#padding the documents to a fixed length

[[   0    0    0    0 3560  977 8012 9122]
 [   0    0    0    0 3560  977 8012 9045]
 [   0    0    0    0 4905  977 8012 9122]
 [   0 1170 4905 8297 8012 9122 3350 2489]
 [   0    0 3560 8297 8012 9122 3350 2489]
 [   0    0    0    0 9105   28 8064 2489]
 [   0    0    0 1086 6153 4101   20  629]
 [   0  629 3350 3512 5399   20 3198 5379]]


In [ ]:
#feature dimension
dim=10
model=Sequential()
model.add(Embedding(voc_size,output_dim=dim,input_length=sent_length))
model.compile('adam','mse')

In [15]:
model.summary()


Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 8, 10)             100000    
                                                                 
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [19]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 15ms/step


array([[[ 1.98693015e-02,  4.31375615e-02, -4.62446213e-02,
          3.63599136e-03, -1.31194480e-02,  2.97301747e-02,
          3.75328213e-03,  4.59327437e-02,  1.89881809e-02,
         -3.75977270e-02],
        [ 1.98693015e-02,  4.31375615e-02, -4.62446213e-02,
          3.63599136e-03, -1.31194480e-02,  2.97301747e-02,
          3.75328213e-03,  4.59327437e-02,  1.89881809e-02,
         -3.75977270e-02],
        [ 1.98693015e-02,  4.31375615e-02, -4.62446213e-02,
          3.63599136e-03, -1.31194480e-02,  2.97301747e-02,
          3.75328213e-03,  4.59327437e-02,  1.89881809e-02,
         -3.75977270e-02],
        [ 1.98693015e-02,  4.31375615e-02, -4.62446213e-02,
          3.63599136e-03, -1.31194480e-02,  2.97301747e-02,
          3.75328213e-03,  4.59327437e-02,  1.89881809e-02,
         -3.75977270e-02],
        [-1.93920974e-02, -2.34123711e-02,  1.58185251e-02,
         -2.65517831e-02,  2.84568220e-03, -4.82629798e-02,
          2.47260965e-02, -3.97574902e-02,  3.630622